openapi: 3.0.0
info:
  title: Special Description Sample
  version: 1.0.0
  description: "Description with newlines\nand \"double quotes\", \\backslashes\\, \tand tabs."
paths:
  /test:
    get:
      responses:
        200:
          description: OK
